# Generated by Django 5.0.1 on 2024-03-20 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('CUST', 'Customer'), ('WAIT', 'Waiter'), ('CHEF', 'Chef')], default='CUST', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.TextField()),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('calories', models.IntegerField()),
                ('allergies', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Backend.users')),
                ('preferences', models.TextField()),
                ('allergies', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KitchenStaff',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Backend.users')),
                ('shift', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Waiters',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Backend.users')),
                ('shift', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_number', models.IntegerField(primary_key=True, serialize=False)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'Order Placed.'), ('I', 'Order In Progress.'), ('C', 'Order Completed.')], default='P', max_length=1)),
                ('items', models.TextField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.tables')),
            ],
        ),
    ]
