# Generated by Django 5.0.1 on 2024-03-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('P', 'Order Placed.'), ('I', 'Order In Progress.'), ('C', 'Order Completed.'), ('D', 'Delivered.')], default='P', max_length=1),
        ),
    ]
