# Generated by Django 5.0.1 on 2024-03-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('P', 'Order Placed.'), ('I', 'Order In Progress.'), ('C', 'Order Cancelled.'), ('D', 'Order Delivered.')], default='P', max_length=1),
        ),
    ]
